# Generated by Django 6.0.7 on 2026-08-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_booking_seat_position_remove_booking_seats_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('seat_number', 'flight')},
        ),
    ]
