# Generated by Django 6.0.7 on 2026-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_seat_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_seat_prices',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_class',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Premium Economy', 'Premium Economy'), ('Business', 'Business'), ('First Class', 'First Class')], default='Economy', max_length=20),
        ),
    ]
