# Generated by Django 6.0.7 on 2026-08-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_rename_price_flight_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_transaction_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
