# Generated by Django 6.0.7 on 2026-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_booking_mpesa_receipt_number_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
