# Generated by Django 6.0.7 on 2026-09-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_booking_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.PositiveIntegerField(default=120),
            preserve_default=False,
        ),
    ]
